
# Change these first
owner: BlocklabNL # Your GitHub organization or username, where this repository lives
repo: ebl-upptime # The name of this repository

sites:
  - name: Naviporta identity provider (test)
    url: https://id-test.naviporta.dev
  - name: Naviporta identity provider (staging)
    url: https://id-staging.naviporta.dev
  - name: Naviporta identity provider (production)
    url: https://id.naviporta.com

  - name: Naviporta vault (test)
    url: https://vault-test.naviporta.dev/v1
  - name: Naviporta vault (staging)
    url: https://vault-staging.naviporta.dev/v1
  - name: Naviporta vault (production)
    url: https://vault.naviporta.com/v1

  - name: OpenCerts.io
    url: https://api.opencerts.io/

status-website:
  baseUrl: /ebl-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ebl Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
